title: Canal Coding Camp
meta_author: +DeDev
gh_repo: "https://github.com/alexduros/canal-coding-camp/"


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: "000" #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

camp:
  date: Journ√©e du 27 avril 2017